### ISSUE TITLE
Missing Haha.jpg at /tmp/haha.jpg and Missing Refresh Token

### ISSUE THREAD

**Issue by AaronGearheart** [Om-Thorat/Readme-Spotify-Now-Playing#4]
Main.py is supposed to give the refresh but doesn't exist and the index.py doesn't get it and give it to the user. Haha.jpg also doesn't exist or isn't generated by the once existent main.py

**Comment by Om-Thorat** [comment]
Index.py when run with the correct credentials produces a refresh token and stores it in a file.

**Comment by AaronGearheart** [comment]
Any chance you can upload the haha.jpg which I assume is the background in this case?

**Comment by Om-Thorat** [comment]
The card @AaronGearheart is entirely html css haha.jpg here is the album cover which is saved right before it's accessed in the same function, it's a code generated file not a specific one that i have uploaded.

**Comment by AaronGearheart** [comment]
I tried running it giving it my secret and ID and got an error because tmp/haha.jpg didn't exist and after looking in the index.py never saw it saving the refresh or even getting it from the Spotify api at all I saw it plugging it back in but never recieve other than os enviro

**Comment by Om-Thorat** [comment]
![image](https://github.com/Om-Thorat/Readme-Spotify-Now-Playing/assets/76207818/77c2fa67-14a2-4432-a021-f9533b1aee8c)

I tried running the whole thing again and it worked may i please see your code and error?

**Comment by Om-Thorat** [comment]
Also pushed a new commit removing the entire need for saving and haha.jpg in the first hand

**Comment by AaronGearheart** [comment]
![image](https://github.com/Om-Thorat/Readme-Spotify-Now-Playing/assets/92656623/071a6f3c-28ee-4ebd-b357-a280913c87b9)
`from flask import Flask,Response,request,redirect,render_template
import spotipy
from spotipy import util
from pathlib import Path
import re
import base64
from PIL import Image
import requests
from io import BytesIO
import random
from spotipy import oauth2
import os

cwd = Path.cwd()
cwd = re.sub(r"\\",r"/",str(cwd))
CLIENT_ID = "MY_ID"
CLIENT_SECRET = "MY_SECRET"
scope = "user-read-playback-state user-read-recently-played"
redirect_uri = "http://127.0.0.1:5000/spotify"

app = Flask(__name__)
try:
    Refresh = os.environ['REFRESH']
    data = {
        "grant_type": "refresh_token",
        "refresh_token": Refresh,
        }

    res = requests.post(
        "https://accounts.spotify.com/api/token",
        data={
            "grant_type": "refresh_token",
            "refresh_token": Refresh,
            "client_id": CLIENT_ID,
            "client_secret": CLIENT_SECRET,
        },
    )
    token = res.json()['access_token']
except:
    token = util.prompt_for_user_token("",scope, CLIENT_ID, CLIENT_SECRET, redirect_uri,cache_path=f"token.json")
sp = spotipy.Spotify(auth=token)
def spotify():
    try:
        current = (sp.current_playback())
        songname = (current['item']['name'])
        artist = (current['item']['artists'][0]['name'])
        cover = (current['item']['album']['images'][0]['url'])
        return ["Now Playing",songname,cover,artist]
    except:
        current = sp.current_user_recently_played(limit=1)
        songname = (current['items'][0]['track']['name'])
        artist = (current['items'][0]['track']['artists'][0]['name'])
        cover = (current['items'][0]['track']['album']['images'][0]['url'])
        return ["last played",songname,cover,artist]
    
@app.route('/')
def hi():
     return "Um?"

@app.route('/spotify')
def cool():
        info = spotify()
        print(info)
        songname = info[1].replace("&","&amp;")
        artist = info[3].replace("&","&amp;")
        response = requests.get(info[2])
        img = Image.open(BytesIO(response.content))
        img.save(f"/tmp/haha.jpg",format="JPEG")
        with open(f"/tmp/haha.jpg","rb") as img_file:
            imgstr = base64.b64encode(img_file.read()).decode()
        bars = ""
        for i in range(0,32):
            bars = bars + (f'<div class="bar" style="animation-delay: {random.randint(500,800)}ms; animation-duration: {random.randint(800,1000)}ms"></div>')
        data = {
            "status" : info[0],
            "songname":songname,
            "artist":artist,
            "imgstr":imgstr,
            "bars":bars
        }
        aight = render_template("card.html.j2",**data)
        resp = Response(aight,mimetype='image/svg+xml')
        resp.headers['Cache-Control'] = 'public, max-age=0, must-revalidate'
        return resp


app.run(debug=True)`

Only changes I made was uncommenting the app.run and and changing the os.environ("ID") thing (not sure of the original) to just flat out defining. Never saved a .json and tbh don't even see the code to do so

**Comment by AaronGearheart** [comment]
Works with new commit but you left your spotify details in there!

**Comment by Om-Thorat** [comment]
> Works with new commit but you left your spotify details in there!

😭  welp no worries i'll reset them

**Comment by Om-Thorat** [comment]
> ![image](https://private-user-images.githubusercontent.com/92656623/319368106-071a6f3c-28ee-4ebd-b357-a280913c87b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxODE2MTYsIm5iZiI6MTcxMjE4MTMxNiwicGF0aCI6Ii85MjY1NjYyMy8zMTkzNjgxMDYtMDcxYTZmM2MtMjhlZS00ZWJkLWIzNTctYTI4MDkxM2M4N2I5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDIxNTUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4ODFjY2I0YTE0MWZjYmZiZmJkOGEyYTRiYWFiNzEwYjAwY2VmODcxOGI1NjdhN2ZmYWQxNjM4ZDY0MjAxYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3_LysOGknMnWP15M3cYHUbL1fUsd9iJm1zxGSdi5v4w) `from flask import Flask,Response,request,redirect,render_template import spotipy from spotipy import util from pathlib import Path import re import base64 from PIL import Image import requests from io import BytesIO import random from spotipy import oauth2 import os
> 
> cwd = Path.cwd() cwd = re.sub(r"\",r"/",str(cwd)) CLIENT_ID = "MY_ID" CLIENT_SECRET = "MY_SECRET" scope = "user-read-playback-state user-read-recently-played" redirect_uri = "http://127.0.0.1:5000/spotify"
> 
> app = Flask(**name**) try: Refresh = os.environ['REFRESH'] data = { "grant_type": "refresh_token", "refresh_token": Refresh, }
> 
> ```
> res = requests.post(
>     "https://accounts.spotify.com/api/token",
>     data={
>         "grant_type": "refresh_token",
>         "refresh_token": Refresh,
>         "client_id": CLIENT_ID,
>         "client_secret": CLIENT_SECRET,
>     },
> )
> token = res.json()['access_token']
> ```
> 
> except: token = util.prompt_for_user_token("",scope, CLIENT_ID, CLIENT_SECRET, redirect_uri,cache_path=f"token.json") sp = spotipy.Spotify(auth=token) def spotify(): try: current = (sp.current_playback()) songname = (current['item']['name']) artist = (current['item']['artists'][0]['name']) cover = (current['item']['album']['images'][0]['url']) return ["Now Playing",songname,cover,artist] except: current = sp.current_user_recently_played(limit=1) songname = (current['items'][0]['track']['name']) artist = (current['items'][0]['track']['artists'][0]['name']) cover = (current['items'][0]['track']['album']['images'][0]['url']) return ["last played",songname,cover,artist]
> 
> @app.route('/') def hi(): return "Um?"
> 
> @app.route('/spotify') def cool(): info = spotify() print(info) songname = info[1].replace("&","&") artist = info[3].replace("&","&") response = requests.get(info[2]) img = Image.open(BytesIO(response.content)) img.save(f"/tmp/haha.jpg",format="JPEG") with open(f"/tmp/haha.jpg","rb") as img_file: imgstr = base64.b64encode(img_file.read()).decode() bars = "" for i in range(0,32): bars = bars + (f'
> ')
> data = {
> "status" : info[0],
> "songname":songname,
> "artist":artist,
> "imgstr":imgstr,
> "bars":bars
> }
> aight = render_template("card.html.j2",**data)
> resp = Response(aight,mimetype='image/svg+xml')
> resp.headers['Cache-Control'] = 'public, max-age=0, must-revalidate'
> return resp
> 
> app.run(debug=True)`
> 
> Only changes I made was uncommenting the app.run and and changing the os.environ("ID") thing (not sure of the original) to just flat out defining. Never saved a .json and tbh don't even see the code to do so

It saves the json right here ` token = util.prompt_for_user_token("",scope, CLIENT_ID, CLIENT_SECRET, redirect_uri,cache_path=f"token.json")` in this part

and the issue w haha.jpg must be about from where you executed the file and the cwd i think but yea the newer method is better sorry from my dumb old self saving the image then converting to b64!
